import 'package:flutter/material.dart';

class AppTheme {
  static ThemeData get lightTheme {
    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.light,
      primaryColor: const Color(0xFF405F90),
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF405F90),
        foregroundColor: Colors.white,
        elevation: 4,
      ),
      cardTheme: const CardTheme(color: Color(0xFF405F90), elevation: 4),
      canvasColor: const Color(0xFFF9F9FF),
      scaffoldBackgroundColor: const Color(0xFFF9F9FF),
      cardColor: const Color(0xFFF9F9FF),
      dividerColor: const Color(0x1F191C20),
      splashColor: const Color.fromARGB(123, 43, 43, 43),
      highlightColor: const Color(0x66BCBCBC),
      focusColor: const Color(0x1F000000),
      hoverColor: const Color(0x0A000000),
      shadowColor: const Color.fromARGB(255, 137, 177, 241),
      dialogBackgroundColor: const Color(0xFFF9F9FF),
      indicatorColor: Colors.white,
      colorScheme: ColorScheme(
        brightness: Brightness.light,
        primary: const Color(0xFF405F90),
        onPrimary: Colors.white,
        primaryContainer: const Color(0xFFD6E3FF),
        onPrimaryContainer: const Color(0xFF001B3D),
        secondary: const Color(0xFF555F71),
        onSecondary: Colors.white,
        secondaryContainer: const Color(0xFFD9E3F9),
        onSecondaryContainer: const Color(0xFF121C2B),
        tertiary: const Color(0xFF6F5675),
        onTertiary: Colors.white,
        tertiaryContainer: const Color(0xFFF9D8FD),
        onTertiaryContainer: const Color(0xFF28132F),
        error: const Color(0xFFBA1A1A),
        onError: Colors.white,
        errorContainer: const Color(0xFFFFDAD6),
        onErrorContainer: const Color(0xFF410002),
        background: const Color(0xFFF9F9FF),
        onBackground: const Color(0xFF191C20),
        surface: const Color(0xFFF9F9FF),
        onSurface: const Color(0xFF191C20),
        outline: const Color(0xFF74777F),
        shadow: const Color(0xFF000000),
        surfaceVariant: const Color(0xFF44474E),
        onSurfaceVariant: const Color(0xFFC4C6CF),
        inverseSurface: const Color(0xFF2E3036),
        onInverseSurface: const Color(0xFFF0F0F7),
        surfaceTint: const Color(0xFF405F90),
      ),
      buttonTheme: ButtonThemeData(
        minWidth: 88,
        height: 36,
        padding: const EdgeInsets.symmetric(horizontal: 16),
        layoutBehavior: ButtonBarLayoutBehavior.padded,
        alignedDropdown: false,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
      ),
      iconTheme: const IconThemeData(color: Color(0xDD000000)),
      primaryIconTheme: const IconThemeData(color: Colors.white),
      textTheme: const TextTheme(
        bodyLarge: TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.5,
          color: Color.fromARGB(255, 0, 0, 0),
        ),
        bodyMedium: TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
          color: Color(0xFF191C20),
        ),
        bodySmall: TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.4,
          color: Color(0xFF191C20),
        ),
        displayLarge: TextStyle(
          fontSize: 96,
          fontWeight: FontWeight.w300,
          letterSpacing: -1.5,
          color: Color(0xFF191C20),
        ),
        displayMedium: TextStyle(
          fontSize: 60,
          fontWeight: FontWeight.w300,
          letterSpacing: -0.5,
          color: Color(0xFF191C20),
        ),
        displaySmall: TextStyle(
          fontSize: 48,
          fontWeight: FontWeight.w400,
          letterSpacing: 0,
          color: Color(0xFF191C20),
        ),
        headlineLarge: TextStyle(
          fontSize: 40,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
          color: Color(0xFF191C20),
        ),
        headlineMedium: TextStyle(
          fontSize: 34,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
          color: Color(0xFF191C20),
        ),
        headlineSmall: TextStyle(
          fontSize: 24,
          fontWeight: FontWeight.w400,
          letterSpacing: 0,
          color: Color(0xFF191C20),
        ),
        titleLarge: TextStyle(
          fontSize: 20,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.15,
          color: Color(0xFF191C20),
        ),
        titleMedium: TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.15,
          color: Color(0xFF191C20),
        ),
        titleSmall: TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.1,
          color: Color(0xFF191C20),
        ),
        labelLarge: TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w500,
          letterSpacing: 1.25,
          color: Color(0xFF191C20),
        ),
        labelMedium: TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w400,
          letterSpacing: 1.5,
          color: Color(0xFF191C20),
        ),
        labelSmall: TextStyle(
          fontSize: 10,
          fontWeight: FontWeight.w400,
          letterSpacing: 1.5,
          color: Color(0xFF191C20),
        ),
      ),
    );
  }
}
